name: Regional Plan Association
markdown: redcarpet
permalink: pretty
destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache", "tmp", "vendor"]
root: /rpa/

prose:
  rooturl: '_posts'
  siteurl: 'http://volkanunsal.github.io/rpa/'
  relativeLinks: 'http://volkanunsal.github.io/rpa/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts/chapters:
      - name: "class"
        field:
          element: "hidden"
          value: "chapter"
      - name: "page_name"
        field:
          element: "hidden"
          value: "STATE OF THE REGION"
      - name: "layout"
        field:
          element: "hidden"
          value: "chapter"
      - name: "chapter_number"
        field:
          element: "hidden"
          value: ""
      - name: "chapter_title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "chapter_intro"
        field:
          element: "text"
          label: "Intro"
          value: ""
