name: Regional Plan Association
markdown: redcarpet
destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache", "tmp", "vendor"]
root: /rpa/

prose:
  rooturl: 'c'
  siteurl: 'http://volkanunsal.github.io/rpa/'
  relativeLinks: 'http://volkanunsal.github.io/rpa/links.jsonp'
  media: 'media'
  metadata:
    c:
      - name: "class"
        field:
          element: "hidden"
          value: "ch2"
      - name: "page_name"
        field:
          element: "hidden"
          value: "STATE OF THE REGION"
      - name: "layout"
        field:
          element: "hidden"
          value: "chapter"
      - name: "chapter_title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "chapter_intro"
        field:
          element: "text"
          label: "Intro"
          value: ""
      - name: "map_id"
        field:
          label: "Map Id"
          element: "select"
          placeholder: "Choose a map"
          options:
            - name: "Discretionary Income"
              value: "discretionary"
            - name: "School Performance"
              value: "schools"
            - name: "Vulnerable Infrastructure"
              value: "vulnerableInfra"
            - name: "Walkability"
              value: "walkability"
      - name: "chapter_number"
        field:
          element: "text"
          label: "Chapter Number"
          value: ""
