name: Regional Planning Association
markdown: redcarpet
destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache", "tmp"]
root: ""
# root: "/rpa"
